### ISSUE TITLE
Edge 把 crx 拖进去没有任何作用

### ISSUE THREAD

**Issue by GF-Huang** [lmk123/highlight-translator-docs#9]
![image](https://user-images.githubusercontent.com/4510984/107470874-0f93ff80-6ba7-11eb-9176-0d38c40599af.png)

**Comment by GF-Huang** [comment]
打开开发人员模式就可以了，建议加上这个提示，搞了半天很恼火。
![image](https://user-images.githubusercontent.com/4510984/107470975-4407bb80-6ba7-11eb-80cd-1770d9d14871.png)

**Comment by lmk123** [comment]
好的
